# 
# Copyright (C) 2020 ArtXIA <https://github.com/artxia>
# <https://github.com/artxia/Action-NotionSite.git>
#

name: Deploy to Pages

on:
  schedule:
    - cron: "*/20 * * * *"
  push:
    branches:
      - master
    
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2

      - name: Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --remote
          sudo apt-get -y update
          sudo apt-get -y install chromium-browser
          sudo apt-get -y install google-chrome-stable

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and Run
        run: |
          ls
          pip install -r loconotion/requirements.txt
          python loconotion kb.toml > test.log 2>&1

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: loconotion/dist
          CLEAN: true
          SINGLE_COMMIT: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 6
